// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXtIzizo3-FxrWY-ZAoClqmOixjWJtK-g',
    appId: '1:939518696890:web:905140024f2ac0732f5183',
    messagingSenderId: '939518696890',
    projectId: 'safeeat-c2512',
    authDomain: 'safeeat-c2512.firebaseapp.com',
    storageBucket: 'safeeat-c2512.firebasestorage.app',
    measurementId: 'G-78GM3SBBLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOsZuaUko756C9rHkjbOSdfoMEcXe182k',
    appId: '1:939518696890:android:52601338028cc2302f5183',
    messagingSenderId: '939518696890',
    projectId: 'safeeat-c2512',
    storageBucket: 'safeeat-c2512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwevfOhbFGQEwVmyRkl96C66_V6vNfmiU',
    appId: '1:939518696890:ios:d6b7bc9bcd363bf22f5183',
    messagingSenderId: '939518696890',
    projectId: 'safeeat-c2512',
    storageBucket: 'safeeat-c2512.firebasestorage.app',
    iosBundleId: 'com.example.safeEatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwevfOhbFGQEwVmyRkl96C66_V6vNfmiU',
    appId: '1:939518696890:ios:d6b7bc9bcd363bf22f5183',
    messagingSenderId: '939518696890',
    projectId: 'safeeat-c2512',
    storageBucket: 'safeeat-c2512.firebasestorage.app',
    iosBundleId: 'com.example.safeEatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXtIzizo3-FxrWY-ZAoClqmOixjWJtK-g',
    appId: '1:939518696890:web:a959f3d31bdee3262f5183',
    messagingSenderId: '939518696890',
    projectId: 'safeeat-c2512',
    authDomain: 'safeeat-c2512.firebaseapp.com',
    storageBucket: 'safeeat-c2512.firebasestorage.app',
    measurementId: 'G-5MSLYN7J0C',
  );
}
